name: Pytest  Docker
on: [push]
jobs:
  build:
    name: Pytest in Pipenv
    runs-on: ubuntu-latest 
    container:
      image: docker://xlolux/ic_docker:latest
    steps:
    - uses: actions/checkout@v2
    - name: Test with pytest
      run: |
         pytest